### ISSUE TITLE
Help on the "proper way" to build a protocol for DIHARD database with conflicting URI

### ISSUE THREAD

**Issue by hadware** [pyannote/pyannote-database#16]
As you know, i'm building the database "extension" for DiHard2. Their database format is a bit tricky, and I want the user to have to the smallest amount of work possible to do before being able to use the extension.

Here's the setup: the dihard2 data is provided in two archives, which, once unzipped, form two subfolder : `dihard2/dev/` and `dihard2/test/` (there isn't any train data, so this is where pyannote's other databases extensions and the metaprotocol pattern will come in really handy).

Here's the catch: in both folders, the audio files (encoded in flac) share basically the same path and **there are some conflicting uri's**. Thus, a `~/.pyannote/database.yml` pattern to get **only** the `dev` files would be
` path/to/dihard_data/dev/data/single_channel/flac/{uri}.flac`

and a pattern to match only the `test` files would be
` path/to/dihard_data/test/data/single_channel/flac/{uri}.flac`

**The real catch is: there are some uri's that are the same, yet not referencing the same audio file**

There is a simple yet ugly solution: have the user run a bash script that would be provided in the repo that would somehow fix this, but it would imply also parsing the `.rttm` files and modify the uri's in there as well. Not pretty, not optimal, not my style.

I've looked a bit into the `FileFinder` class, and it seems it uses the `format` fonction to render the "matched" audio file's path: `path = path_template.format(uri=uri, database=database, **kwargs) `

My guess is that it's maybe possible, in your infrastructure, to use this kind of generic patch in the `~/.pyannote/database.yml` file:
` path/to/dihard_data/{split}/data/single_channel/flac/{uri}.flac`

And the, in my implementation of a protocol have something like this:
```python3
class DIHARD2SingleChannelProtocol(SpeakerDiarizationProtocol):
    """DIHARD speaker diarization protocol """

    def dev_iter(self):
        for annot_filepath in self.load_RTTM_files():
             # parse stuff

            current_file = {
                'database': 'DIHARD2',
                'uri': uri,
                'channel': 1,
                'split': 'dev', # <======== added to be then used by the format function
                'annotated': ...,
                'annotation': ...}
            yield current_file

    def tst_iter(self):
        for test_file in test_data:
            current_file = {
                'database': 'DIHARD2',
                'uri': uri,
                'channel': 1,
                'split': 'test', # <======== added to be then used by the format function
                'annotated': ...,}
            yield current_file
```

Do you think that's feasible? Do you have any better way to solve this kind of problem since you have a much better understanding of pyannote?

**Comment by hbredin** [comment]
I noticed the same issue when working on DIHARD challenge. I would argue that this is bad practice from DIHARD organizers to use the same name for different files... but now the harm is done :)

The solution based on the additional `split` field should work. 
I don't foresee any issue with the rest of `pyannote` ecosystem (though I might be wrong because I haven't had my morning coffee yet...)

An alternative is to use `/path/to/dihard_data/{uri}.flac` as matching pattern and use  `dev/data/single_channel/flac/DHxxxx` as actual `uri`. This might cause an issue with `pyannote-metrics.py` evaluation script. In particular, `get_hypothesis` should probably be updated to support this kind of `uri` mismatch: https://github.com/pyannote/pyannote-metrics/blob/efa42b99f420210e4eb0225a1be972718b0a6bc2/scripts/pyannote-metrics.py#L142-L181

**Comment by hadware** [comment]
Well, i'm going to try the 'split' method out and see how it goes.

Regarding the alternative method, I gazed intensely at the code but couldn't see anything that would be disturbed by having subpaths as uri's.

**Comment by geniki** [comment]
In our case at least, I haven't seen the benefit of having the automatic `FileFinder` over using fixed paths within a dataset. As a downside, it seems to take some time to find all files for a bigger dataset, slowing startup time.

**Comment by hadware** [comment]
Just so you know, we decided (someone else from CoML) to just remodel the dataset with a script and use a good ol' "Generic speaker diarization protocols" to save us the hassle of having to implement an actual DB module.

**Comment by hbredin** [comment]
FYI, I am currently [working on v2](https://github.com/pyannote/pyannote-audio/tree/v2) of `pyannote.audio` where you will be able to use your own piece of code in place of `FileFinder`, [by overriding the "audio" preprocessors](https://github.com/pyannote/pyannote-audio/commit/ec57e00be3c9e762a17d23f427e59ee0ebac47b7).

I am also playing with [lazy loading](https://github.com/pyannote/pyannote-database/commit/df34485afeaef060d5fc7a939a43821eb8ecf092) in `pyannote.database` so that training starts as soon as possible (without looking for all files first). If you want to try it (and provide me with feedback), simply checkout and install `lazy_preprocessors` branch of `pyannote.database`.

**Comment by hbredin** [comment]
Closing in preparation of `pyannote.database` 4.0 which comes with a complete rewrite of custom protocols. See [custom](https://github.com/pyannote/pyannote-database/blob/custom/README.md) branch for details.
