### ISSUE TITLE
Warning: Existing key "annotation" may have been modified.

### ISSUE THREAD

**Issue by PaulLerner** [pyannote/pyannote-database#56]
Hi,

I keep getting this warning when training a pipeline (this issue might have to be transferred) `/mnt/beegfs/projects/plumcot/pyannote/pyannote-database/pyannote/database/protocol/protocol.py:128: UserWarning: Existing key "annotation" may have been modified.`

This only happens during the first trial (i.e. the first iteration over the whole database subset) but it didn't happen before 4.0

**Comment by hbredin** [comment]
This is due to the fact that `annotation` is now cropped to `annotated` extent using a preprocessor:

https://github.com/pyannote/pyannote-database/blob/3852372e14f439e6915c8a8fa5db286e1c0c6b76/pyannote/database/protocol/speaker_diarization.py#L178-L180

In `pyannote.database` 3.x, it was done directly in `add_custom_protocol` without any warning.

We could be smarter and only print this warning when the value actually changed.
Relevant code is here:
https://github.com/pyannote/pyannote-database/blob/a34386d3179e4ab0b6a1c7010191f6eefa4e233c/pyannote/database/protocol/protocol.py#L125-L128

Pull request welcome ;-)
